repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v1.9.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
        language: system
        exclude: integration_tests
